runtime: python312

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GOOGLE_CLOUD_PROJECT: "shaped-repeater-446316-t9"  # Replace with your actual project ID

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
